# Generated by Django 5.2 on 2025-04-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fan',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='ustoz',
            options={'verbose_name': 'Ustoz', 'verbose_name_plural': 'Ustozlar'},
        ),
        migrations.AlterModelOptions(
            name='yunalish',
            options={'verbose_name': 'Yunalish', 'verbose_name_plural': 'Yunalishlar'},
        ),
    ]
